### Register a user POST /auth/register
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "email": "varunm@altorsolutions.com", 
    "password": "vmm@4202334", 
    "employeeId": "99734820", 
    "first_name": "Varun", 
    "last_name": "Menon"
}

### Login a user POST /auth/login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "varunm@altorsolutions.com", 
    "password": "vmm@4202334", 

}