
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
      - PORT=8000
