version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8000
      # MongoDB Atlas connection string should be provided via .env file
      # - MONGODB_URI=mongodb+srv://<username>:<password>@<cluster>.mongodb.net/<database>?retryWrites=true&w=majority
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRE=30d
      - CORS_ORIGIN=http://localhost:3000
    env_file:
      - .env

volumes:
  mongodb_data: 